[tool:pytest]
testpaths  = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --alluredir=allure-results --tb=short -v -s
markers =
    smoke: smoke tests
    regression: regression tests
    e2e: end-to-end tests
    schema: schema validation tests
 